from .exibirEstatistica import exibirEstatistica
from .listarEstatistica import listarEstatistica
from .registrarEstatistica import registrarEstatistica
from .salvarEstatistica import salvarEstatistica
from .apagarEstatisticas import apagarEstatisticas
from .resetarServidorEstatisticas import resetarServidorEstatisticas