DATABASE_URL = "sqlite:///database/database.db"

# ALIASES
DATANOODLE_MANAGER_ALIASES = 'DATANOODLE_MANAGER_SERVER'
PLAYKITE_VIDEO_MANAGER_ALIASES = 'PLAYKITE_VIDEO_MANAGER_SERVER'

# MONITORING
INTERVAL_PING = 0.3