HOST = '127.0.0.1'
PORT = 5000

DATABASE_URL = "sqlite:///database/database.db"
REPLIKATE_DATANODE_MANAGER_ALIASES = 'DATANODE_MANAGER_SERVER'
REPLIKATE_VIDEO_MANAGER_ALIASES = 'VIDEO_MANAGER_SERVER'
MONITOR_ALIASES = 'MONITOR_SERVER'
ALIAS_FILE = 'alias.txt'
INTERVAL_PING = 1