DATABASE_URL = "sqlite:///database/database.db"

# ALIASES
DATANOODLE_DATANODE_MANAGER_ALIASES = 'DATANOODLE_MANAGER_SERVER'
PLAYKITE_VIDEO_MANAGER_ALIASES = 'PLAYKITE_VIDEO_MANAGER_SERVER'
MONITOR_ALIASES = 'MONITOR_SERVER'

# ALIAS MANAGER
ALIAS_FILE = 'alias.txt'
UPLOAD_FILE_PATH = './database/uploads'

# MONITORING
INTERVAL_PING = 0.3