"""empty message

Revision ID: 491bd6d31e0e
Revises: 
Create Date: 2024-01-20 16:08:29.898317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491bd6d31e0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datanode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videoinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datanode_videoinfo_association',
    sa.Column('datanode_id', sa.Integer(), nullable=False),
    sa.Column('videoinfo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datanode_id'], ['datanode.id'], ),
    sa.ForeignKeyConstraint(['videoinfo_id'], ['videoinfo.id'], ),
    sa.PrimaryKeyConstraint('datanode_id', 'videoinfo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datanode_videoinfo_association')
    op.drop_table('videoinfo')
    op.drop_table('datanode')
    # ### end Alembic commands ###
