"""empty message

Revision ID: 91b209a0fa78
Revises: 491bd6d31e0e
Create Date: 2024-01-20 16:10:28.336308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b209a0fa78'
down_revision: Union[str, None] = '491bd6d31e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videoinfo', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videoinfo', 'description')
    # ### end Alembic commands ###
