"""monitor

Revision ID: c34dcd11b329
Revises: 82d7d9191824
Create Date: 2024-02-04 21:29:22.947222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34dcd11b329'
down_revision: Union[str, None] = '82d7d9191824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datanode', sa.Column('alias', sa.String(), nullable=False))
    op.drop_column('datanode', 'host')
    op.drop_column('datanode', 'status')
    op.drop_column('datanode', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datanode', sa.Column('port', sa.INTEGER(), nullable=False))
    op.add_column('datanode', sa.Column('status', sa.VARCHAR(), nullable=False))
    op.add_column('datanode', sa.Column('host', sa.VARCHAR(), nullable=False))
    op.drop_column('datanode', 'alias')
    # ### end Alembic commands ###
