"""empty message

Revision ID: ac76c4146641
Revises: 3c1947c50bd6
Create Date: 2024-02-09 10:45:57.336801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac76c4146641'
down_revision: Union[str, None] = '3c1947c50bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('path', sa.String(), nullable=False))
    op.drop_column('videos', 'blob')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('blob', sa.BLOB(), nullable=False))
    op.drop_column('videos', 'path')
    # ### end Alembic commands ###
