HOST = '127.0.0.1'
PORT = 4000
DATABASE_URL = "sqlite:///database/database.db"
INTERVAL_RESET_STATUS = 3

REPLIKATE_DATANODE_MANAGER_ALIASES = 'DATANODE_MANAGER_SERVER'
REPLIKATE_VIDEO_MANAGER_ALIASES = 'VIDEO_MANAGER_SERVER'