REPLIKATE_DATANODE_MANAGER_ALIASES = 'DATANODE_MANAGER_SERVER'
REPLIKATE_VIDEO_MANAGER_ALIASES = 'VIDEO_MANAGER_SERVER'
STATISTIC_ALIASES = 'STATISTIC_SERVER'
STATISTICS_FILE = 'data.csv'
STATISTICS_LOCATION = './data'
STATISTICS_FILE_PATH = f"{STATISTICS_LOCATION}/{STATISTICS_FILE}"