
# ALIASES
DATANOODLE_DATANODE_MANAGER_ALIASES = 'DATANOODLE_MANAGER_SERVER'
PLAYKITE_VIDEO_MANAGER_ALIASES = 'PLAYKITE_VIDEO_MANAGER_SERVER'
STATISTIC_ALIASES = 'STATISTIC_SERVER'

## STATISTIKAL STORAGE
STATISTICS_LOCATION = './statistics'
STATISTICS_FILE = 'data.csv'
STATISTICS_LOCATION = './data'
STATISTICS_FILE_PATH = f"{STATISTICS_LOCATION}/{STATISTICS_FILE}"